# NumPy Array Slicing

## Slicing arrays
- #### Slicing in python means taking elements from one given index to another given index.

- #### We pass slice instead of index like this: [start:end].

- #### We can also define the step, like this: [start:end:step].

- #### If we don't pass start its considered 0

- #### If we don't pass end its considered length of array in that dimension

- #### If we don't pass step its considered 1

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])    # Note: The result includes the start index, but excludes the end index.

[2 3 4 5]


In [3]:
print(arr[:])    # prints whole arr

[1 2 3 4 5 6 7]


In [5]:
print(arr[4:])    # start 4th index and print till end

[5 6 7]


In [6]:
print(arr[:4])    # Slice elements from the beginning to index 4 (not included):

[1 2 3 4]


## Negative Slicing
- #### Use the minus operator to refer to an index from the end:

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


### STEP
- #### Use the step value to determine the step of the slicing:

In [10]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [11]:
print(arr[::2])

[1 3 5 7]


## Slicing 2-D Arrays

#### From the second element, slice elements from index 1 to index 4 (not included):

In [12]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [13]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [15]:
print(arr[0:2, 2])    # From both elements, return index 2:

[3 8]


In [16]:
print(arr[0:2, 1:4])    # From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

[[2 3 4]
 [7 8 9]]


# <=== Array Slicing Completed ===>