# Array Attributes

In [2]:
import numpy as np

In [3]:
a1 = np.arange(10) # 1D 
a1 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a2 =np.arange(12, dtype =float).reshape(3,4) # Matrix 
a2 

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [5]:
a3 = np.arange(8).reshape(2,2,2) # 3D --> Tensor 
a3 

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

## ndim 
  - #### To findout given arrays number of dimensions

In [6]:
a1.ndim

1

In [7]:
a2.ndim 

2

In [8]:
a3.ndim

3

## shape 
  - #### gives each item consist of no.of rows and np.of column 

In [9]:
a1.shape # 1D array has 10 Items 

(10,)

In [10]:
a2.shape # 3 rows and 4 columns

(3, 4)

In [11]:
a3.shape # first ,2 says it consists of 2D arrays .2,2 gives no.of rows

(2, 2, 2)

## size 
  - #### gives number of items 

In [12]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [13]:
a3.size # it has 8 items . like shape :2,2,2 = 8

8

In [14]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [15]:
a2.size

12

## item size 
  - #### Memory occupied by the item 

In [16]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a1.itemsize   # bytes

8

In [19]:
a2.itemsize # integer 64 gives = 8 bytes

8

In [20]:
a3.itemsize # integer 32 gives = 4 bytes

8