# Data Types in Python
### By default Python have these data types:

- #### strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- #### integer - used to represent integer numbers. e.g. -1, -2, -3
- #### float - used to represent real numbers. e.g. 1.2, 42.42
- #### boolean - used to represent True or False.
- #### complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

# Data Types in NumPy
### NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

### Below is a list of all data types in NumPy and the characters used to represent them.

- #### i - integer
- #### b - boolean
- #### u - unsigned integer
- #### f - float
- #### c - complex float
- #### m - timedelta
- #### M - datetime
- #### O - object
- #### S - string
- #### U - unicode string
- #### V - fixed chunk of memory for other type ( void )

### Checking the Data Type of an Array
#### The NumPy array object has a property called dtype that returns the data type of the array:

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [2]:
arr

array([1, 2, 3, 4])

In [3]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)    # Get the data type of an array containing strings:

<U6


## Creating Arrays With a Defined Data Type
 #### We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [4]:
arr = np.array([1, 2, 3, 4], dtype='S')    # Create an array with data type string:

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


#### For i, u, f, S and U we can define size as well.

In [9]:
arr1 = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [10]:
arr2 = np.array([11,23,44] , dtype =float)    # float data type

In [11]:
arr3 = np.array([11,23,44] , dtype =bool) # Here True becoz , python treats Non -zero

In [12]:
arr4 = np.array([11,23,44] , dtype =complex)    # comples data type

## Changing Data Type 

In [13]:
print(arr1.dtype) 
print(arr2.dtype) 
print(arr3.dtype)
print(arr4.dtype)

int32
float64
bool
complex128


In [14]:
#astype 
 
x = np.array([33, 22, 2.5]) 
x

array([33. , 22. ,  2.5])

In [16]:
x.astype(int) 

array([33, 22,  2])

## <=== NumPy Data Type Completed ===>