# Numpy

In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.6'

In [3]:
# create a list

In [4]:
list1 = [0,1,2,3,4,5]
list1

[0, 1, 2, 3, 4, 5]

In [5]:
type(list1)

list

In [6]:
# conver list to array

In [7]:
arr = np.array(list1)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
print(type(list1))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [12]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [13]:
np.arange(20,10)    # 1st arg always < 2nd arg

array([], dtype=int64)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.zeros(5)     # PARAMETER TUNNING

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5, dtype=int)     # HYPERPARAMETER TUNNING

array([0, 0, 0, 0, 0])

In [17]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [19]:
np.zeros((10,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [20]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [22]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [23]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

In [24]:
rand(2,3)

NameError: name 'rand' is not defined

In [25]:
random.rand(2,3)

NameError: name 'random' is not defined

In [26]:
np.random.rand(2)

array([0.34148037, 0.71689628])

In [27]:
np.random.rand(2)

array([0.24664095, 0.65791479])

In [28]:
np.random.rand(2)

array([0.90871725, 0.39126528])

In [29]:
np.random.rand(2,3)

array([[0.86630492, 0.1668735 , 0.81464651],
       [0.22430226, 0.81170434, 0.91589384]])

In [30]:
np.random.randint(2)

1

In [39]:
np.random.randint(2,9)

5

In [40]:
np.random.randint(2,9,4)    # generate random integer between 2-9 where 9 is excluded

array([8, 3, 2, 8], dtype=int32)

In [ ]:
otp

In [41]:
np.random.randint(10,40,(10,10))     # 10 * 10 matrix between 10 to 40

array([[27, 37, 27, 31, 35, 28, 22, 13, 21, 30],
       [34, 34, 10, 14, 27, 23, 19, 16, 32, 37],
       [11, 12, 23, 32, 18, 16, 29, 12, 25, 18],
       [31, 37, 10, 16, 34, 13, 17, 34, 26, 32],
       [36, 17, 18, 30, 19, 38, 17, 24, 38, 19],
       [37, 10, 31, 19, 25, 14, 10, 31, 18, 36],
       [33, 20, 38, 23, 37, 30, 13, 38, 23, 29],
       [29, 22, 22, 30, 34, 26, 20, 15, 32, 26],
       [29, 38, 33, 37, 34, 14, 31, 32, 10, 26],
       [31, 22, 32, 27, 30, 26, 16, 17, 23, 18]], dtype=int32)

In [42]:
arr1 = np.random.randint(10,40,(10,10))
print(arr1)

[[14 26 21 39 23 18 26 10 31 25]
 [27 20 39 35 18 34 29 22 26 25]
 [31 33 16 37 16 25 12 37 39 20]
 [19 36 29 38 20 27 19 20 12 26]
 [30 23 30 24 32 11 25 37 25 31]
 [13 32 22 17 13 26 28 28 11 17]
 [36 31 12 15 30 38 10 18 32 20]
 [25 27 11 29 28 35 20 18 31 37]
 [35 25 14 10 13 33 22 24 10 23]
 [32 16 37 39 34 14 23 38 30 12]]


In [44]:
print(arr1)

[[14 26 21 39 23 18 26 10 31 25]
 [27 20 39 35 18 34 29 22 26 25]
 [31 33 16 37 16 25 12 37 39 20]
 [19 36 29 38 20 27 19 20 12 26]
 [30 23 30 24 32 11 25 37 25 31]
 [13 32 22 17 13 26 28 28 11 17]
 [36 31 12 15 30 38 10 18 32 20]
 [25 27 11 29 28 35 20 18 31 37]
 [35 25 14 10 13 33 22 24 10 23]
 [32 16 37 39 34 14 23 38 30 12]]


In [45]:
arr1[5]

array([13, 32, 22, 17, 13, 26, 28, 28, 11, 17], dtype=int32)