# 1. Array Creation Function

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [3]:
b = np.arange(0,10,3)
print("Array b:",b)

Array b: [0 3 6 9]


In [4]:
c = np.zeros((2,3))
print("Array c:\n",c)

Array c:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
d = np.zeros((2,3), dtype=int)
print("Array d:\n",d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [6]:
e = np.ones((3,3), dtype = int)
print("Array e:\n",e)

Array e:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
f = np.eye(4)
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 2. Array Manipulation Functions

In [8]:
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


### Flatten an array

In [9]:
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1)
print("Flattened array:",flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [10]:
t1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [11]:
t1 = np.array([[1,2],[3,4],[5,6]])
transposed = np.transpose(t1)
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3 5]
 [2 4 6]]


In [12]:
s1 = np.array([3,4])
s2 = np.array([4,5])
stacked = np.vstack([s1,s2])
print("stacked arrays:",stacked)

stacked arrays: [[3 4]
 [4 5]]


In [13]:
s1 = np.array([3,4])
s2 = np.array([4,5])
stacked = np.hstack([s1,s2])
print("stacked arrays:",stacked)

stacked arrays: [3 4 4 5]


## 3. Mathematical Function

In [14]:
g = np.array([1,2,3,4])
added = np.add(g,2)
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [15]:
squred = np.power(g,2)
print("Squareed g:", squred)

Squareed g: [ 1  4  9 16]


In [16]:
sqrt_val = np.sqrt(g)
print("Squared root of g:", sqrt_val)

Squared root of g: [1.         1.41421356 1.73205081 2.        ]


In [17]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [18]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g)
print("Dot product of a1 and a:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [ ]:
print(a)
print(a1)

In [19]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,a1)
print("Dot product of a1 and a:",dot_product)

Dot product of a1 and a: 14


# 4. Statistical Function in numpy

In [20]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [21]:
var = np.var(s)
print("Variance of s:", var)

Variance of s: 1.25


In [22]:
std_dev = np.std(s)
print("standard division pf s:", std_dev)

standard division pf s: 1.118033988749895


In [23]:
s

array([1, 2, 3, 4])

In [24]:
minimum = np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [25]:
maximum = np.max(s)
print("Max of s:",maximum)

Max of s: 4


## 5. Linear Algebra Function

In [26]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]]) 
matrix

array([[1, 2],
       [3, 4]])

## 6. Random Sampling Function

In [39]:
random_val = np.random.rand(3)
print("Random values:",random_val)

Random values: [0.84421708 0.19907019 0.28400748]


In [40]:
np.random.seed(0)
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [41]:
rand_int = np.random.randint(0,10,size = 4)
print("Random Integers:",rand_int)

Random Integers: [3 7 9 3]


In [65]:
np.random.seed(0)
rand_int = np.random.randint(0,10,size = 5)
print("Random Integers:",rand_int)

Random Integers: [5 0 3 3 7]


In [79]:
#np.random.seed(0)
rand_int = np.random.randint(0,10,size = 5)
print("Random Integers:",rand_int)

Random Integers: [2 3 8 1 3]


# 7. Boolean & Logical function

In [27]:
# Check if all elements are True

# all
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [28]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [29]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [30]:
# Check if all elements are True
logical_test = np.array([False, True, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [31]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: True


## 8. Set Operations

In [32]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [33]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


## 9. Array attribute Function

In [34]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


## 10. Other Functions

In [35]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [36]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [37]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
