# Array operations 

In [2]:
import numpy as np

In [3]:
z1 = np.arange(12).reshape(3,4) 
z2 = np.arange(12,24).reshape(3,4) 

In [4]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## scalar operations 
  - #### Scalar operations on Numpy arrays include performing addition or subtraction, or multiplication on each element of a Numpy array. 

In [6]:
# arithmetic 
z1 + 2 

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [7]:
# Subtraction 
z1 - 2 

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [8]:
# Multiplication 
z1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [9]:
# power 
z1 ** 2 

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [10]:
# Modulo 
z1 % 2 

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]])

## relational Operators 
  - #### The relational operators are also known as comparison operators, their main function is to return either a true or false based on the value of operands.

In [11]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
z2 > 2 # if 2 is greater than evrythig gives True

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [13]:
z2 > 20 

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

## Vector Operation 
  -  #### We can apply on both numpy array

In [14]:
z1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
z2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [16]:
# Arthemetic 
z1 + z2 # both numpy array Shape is same , we can add item wise 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [17]:
z1 * z2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [18]:
z1 - z2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [19]:
z1 / z2 

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

## Array Functions

In [20]:
k1 = np.random.random((3,3)) 
k1 = np.round(k1*100) 
k1 

array([[80., 77.,  7.],
       [71., 78., 43.],
       [80., 95., 11.]])

In [21]:
# Max 
np.max(k1) 

np.float64(95.0)

In [22]:
# min 
np.min(k1)

np.float64(7.0)

In [23]:
# sum 
np.sum(k1)

np.float64(542.0)

In [24]:
# prod ----> Multiplication 
 
np.prod(k1) 

np.float64(858433063488000.0)

In [25]:
# if we want maximum of every row 
 
np.max(k1, axis = 1) 

array([80., 78., 95.])

In [26]:
# maximum of every column 
 
np.max(k1, axis = 0) 

array([80., 95., 43.])

In [27]:
# product of every column 
 
np.prod(k1, axis = 0) 

array([454400., 570570.,   3311.])

In [28]:
# product of every row
np.prod(k1, axis = 1)

array([ 43120., 238134.,  83600.])

### Statistics related fuctions

In [29]:
# mean 
k1 

array([[80., 77.,  7.],
       [71., 78., 43.],
       [80., 95., 11.]])

In [30]:
np.mean(k1)

np.float64(60.22222222222222)

In [31]:
# mean of every column 
 
k1.mean(axis=0)

array([77.        , 83.33333333, 20.33333333])

In [32]:
# mean of every row
 
k1.mean(axis=1)

array([54.66666667, 64.        , 62.        ])

In [33]:
# median 
 
np.median(k1)

np.float64(77.0)

In [34]:
np.median(k1, axis = 1) 

array([77., 71., 80.])

In [35]:
np.median(k1, axis = 0) 

array([80., 78., 11.])

In [36]:
# Standard deviation 
 
np.std(k1)

np.float64(30.29036435633461)

In [37]:
np.std(k1, axis =0)

array([ 4.24264069,  8.25967446, 16.11072796])

In [40]:
np.std(k1, axis =1)

array([33.72766751, 15.1217283 , 36.57868232])

In [39]:
# variance  
np.var(k1)

np.float64(917.5061728395062)

### Trignometry Functions 

In [41]:
np.sin(k1) # sin 

array([[-0.99388865,  0.99952016,  0.6569866 ],
       [ 0.95105465,  0.51397846, -0.83177474],
       [-0.99388865,  0.68326171, -0.99999021]])

In [42]:
np.cos(k1)

array([[-0.11038724, -0.03097503,  0.75390225],
       [-0.30902273, -0.85780309,  0.5551133 ],
       [-0.11038724,  0.73017356,  0.0044257 ]])

In [43]:
np.tan(k1)

array([[   9.00365495,  -32.26857578,    0.87144798],
       [  -3.0776204 ,   -0.59918   ,   -1.49838734],
       [   9.00365495,    0.93575247, -225.95084645]])

## dot product 
  - #### The numpy module of Python provides a function to perform the dot product of two arrays.

In [44]:
s2 = np.arange(12).reshape(3,4) 
s3 = np.arange(12,24).reshape(4,3) 

In [45]:
s2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [46]:
s3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [47]:
np.dot(s2,s3) # dot product of s2 , s3

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

## Log and Exponents

In [48]:
np.exp(s2) 

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

### round / floor /ceil 

#### 1. round 
#### The numpy.round() function rounds the elements of an array to the nearest integer or to the specified number of decimals.

In [49]:
# Round to the nearest integer 
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
rounded_arr = np.round(arr) 
print(rounded_arr)

[1. 3. 4. 5.]


In [50]:
# Round to two decimals 
arr = np.array([1.234, 2.567, 3.891]) 
rounded_arr = np.round(arr, decimals=2) 
print(rounded_arr)

[1.23 2.57 3.89]


In [51]:
#randomly 
np.round(np.random.random((2,3))*100)

array([[54., 59., 28.],
       [66., 55., 30.]])

### 2. floor 
  - #### The numpy.floor() function returns the largest integer less than or equal to each element of an array.

In [52]:
# Floor operation 
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
floored_arr = np.floor(arr) 
print(floored_arr) 

[1. 2. 3. 4.]


In [53]:
np.floor(np.random.random((2,3))*100) # gives the smallest integer

array([[47., 53., 97.],
       [94., 34.,  8.]])

### 3. Ceil 
 - #### The numpy.ceil() function returns the smallest integer greater than or equal to each element of an array. 

In [54]:
arr = np.array([1.2, 2.7, 3.5, 4.9]) 
ceiled_arr = np.ceil(arr) 
print(ceiled_arr) 

[2. 3. 4. 5.]


In [55]:
np.ceil(np.random.random((2,3))*100) # gives highest integer ex : 7.8 = 8 


array([[28., 97., 30.],
       [45., 92., 34.]])

## Iteration

In [3]:
p1 = np.arange(10) 
p2 = np.arange(12).reshape(3,4) 
p3 = np.arange(8).reshape(2,2,2)

In [4]:
p1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
# Looping on 1D array 
 
for i in p1: 
    print(i) 

0
1
2
3
4
5
6
7
8
9


In [10]:
## Looping on 2D array 
 
for i in p2: 
    print(i) # prints rows 

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [11]:
for i in p3: 
    print(i) 

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [13]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

### print all items in 3D using nditer ---- > first convert in to 1D and applying Loop

In [12]:
for i in np.nditer(p3): 
    print(i) 

0
1
2
3
4
5
6
7


## Reshaping 
#### Transpose ---> Converts rows in to clumns ad columns into rows

In [14]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
np.transpose(p2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [17]:
# Another method 
p2.T 

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [18]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
p3.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

## Ravel 
#### Converting any dimensions to 1D 

In [20]:
p2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
p2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
p3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [23]:
p3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

## Stacking 
- #### Stacking is the concept of joining arrays in NumPy. Arrays having the same dimensions can be stacked. 

In [25]:
# Horizontal stacking 
 
w1 = np.arange(12).reshape(3,4) 
w2 = np.arange(12,24).reshape(3,4) 

In [26]:
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### using hstack for Horizontal stacking 

In [29]:
np.hstack((w1,w2)) 

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [30]:
# Vertical stacking 
w1 

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
w2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

#### using vstack for vertical stacking

In [32]:
np.vstack((w1,w2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting 
#### its opposite of Stacking . 

In [33]:
# Horizontal splitting 
 
w1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.hsplit(w1,2) # splitting by 2

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [35]:
np.hsplit(w1,4) # splitting by 4

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [36]:
# Vertical splitting 
w2 

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
np.vsplit(w2,3) # splittig into 3 rows 

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]