# max,min,reshape

In [1]:
import numpy as np 

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
arr = np.array(my_list) 
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
arr.max()

np.int64(5)

In [7]:
arr.min()

np.int64(0)

In [8]:
arr.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [2]:
arr1 = np.random.randint(10,40,(10,10)) 
print(arr1)

[[17 36 36 32 33 35 18 36 35 13]
 [26 12 27 16 28 35 28 36 19 28]
 [34 31 10 12 36 25 31 38 24 25]
 [30 25 24 36 37 20 29 17 27 18]
 [33 12 11 11 29 29 15 36 27 21]
 [34 12 11 31 17 24 33 20 20 17]
 [25 37 39 31 36 24 13 38 19 26]
 [18 27 12 23 33 22 11 34 39 30]
 [28 36 12 29 29 36 15 35 28 18]
 [22 17 31 39 14 17 36 13 23 23]]


In [3]:
print(arr1) 

[[17 36 36 32 33 35 18 36 35 13]
 [26 12 27 16 28 35 28 36 19 28]
 [34 31 10 12 36 25 31 38 24 25]
 [30 25 24 36 37 20 29 17 27 18]
 [33 12 11 11 29 29 15 36 27 21]
 [34 12 11 31 17 24 33 20 20 17]
 [25 37 39 31 36 24 13 38 19 26]
 [18 27 12 23 33 22 11 34 39 30]
 [28 36 12 29 29 36 15 35 28 18]
 [22 17 31 39 14 17 36 13 23 23]]
