# linspace

- #### It is also called as Linearly space , Linearly separable,in a given range at equal distance it creates points. 

In [1]:
import numpy as np

In [3]:
array = ([[45,34,22,2],[24,55,3,22]]) 
print(array) 

[[45, 34, 22, 2], [24, 55, 3, 22]]


In [4]:
np.linspace(-10,10,10) # here: lower range,upper range ,number of items

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [5]:
np.linspace(-2,12,6)

array([-2. ,  0.8,  3.6,  6.4,  9.2, 12. ])

# identity

 - #### indentity matrix is that diagonal items will be ones and evrything will be zeros

In [6]:
# creating the indentity matrix 
 
np.identity(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])