# Zeros ones & arrange

In [4]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [5]:
print(arr.dtype)

int64


In [6]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [7]:
print(arr.dtype)

float64


In [8]:
arr2 = array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [10]:
arr3 = array([1,2,3,4,5.6],int)
arr3

array([1, 2, 3, 4, 5])

In [11]:
import numpy as np

In [12]:
arr4 = np.linspace(0, 16, 10) # break the code between 10 spaces between 0 to 16 but why decimal becuase we break into parts thats why it is floats
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [13]:
arr5 = np.arange(0,10,2) # arange - as range
arr5

array([0, 2, 4, 6, 8])

In [14]:
arr6 = np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [15]:
list1 = [0,1,2,3,4,5]
list1

[0, 1, 2, 3, 4, 5]

In [16]:
type(list1)

list

In [17]:
arr = np.array(list1)    # conver list to array
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
type(arr)

numpy.ndarray

In [19]:
print(type(list1))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


### Arrange()

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [22]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [23]:
np.arange(20,10)    # 1st arg always < 2nd arg

array([], dtype=int64)

In [24]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

### zeros()

In [25]:
np.zeros(5)     # PARAMETER TUNNING

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros(5, dtype=int)     # HYPERPARAMETER TUNNING

array([0, 0, 0, 0, 0])

In [27]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [28]:
np.zeros((2,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
np.zeros((10,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### ones()

In [30]:
np.ones(4)

array([1., 1., 1., 1.])

In [31]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [32]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [33]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

In [34]:
rand(2,3)

NameError: name 'rand' is not defined

In [35]:
random.rand(2,3)

array([[0.57152649, 0.00313722, 0.31191156],
       [0.56965617, 0.39166287, 0.81231453]])

In [36]:
np.random.rand(2)

array([0.70957822, 0.03112356])

In [37]:
np.random.rand(2)

array([0.34202422, 0.78390033])

In [38]:
np.random.rand(2)

array([0.20067903, 0.28453498])

In [39]:
np.random.rand(2,3)

array([[0.10197408, 0.38352264, 0.2496381 ],
       [0.91361759, 0.51308615, 0.46240293]])

In [43]:
np.random.randint(2)

1

In [44]:
np.random.randint(2,9)

3

In [45]:
np.random.randint(2,9,4)    # generate random integer between 2-9 where 9 is excluded

array([7, 6, 5, 4], dtype=int32)

In [46]:
np.random.randint(10,40,(10,10))     # 10 * 10 matrix between 10 to 40

array([[21, 29, 27, 32, 35, 28, 15, 25, 14, 17],
       [12, 19, 38, 38, 21, 30, 27, 21, 10, 22],
       [13, 37, 10, 13, 33, 24, 11, 13, 37, 35],
       [16, 36, 16, 24, 39, 25, 16, 38, 35, 38],
       [22, 21, 25, 18, 37, 23, 19, 18, 34, 35],
       [19, 15, 36, 30, 37, 10, 21, 38, 17, 37],
       [20, 23, 27, 27, 10, 31, 24, 31, 20, 10],
       [13, 23, 16, 16, 10, 17, 31, 23, 15, 35],
       [22, 14, 28, 17, 21, 20, 27, 18, 28, 32],
       [24, 15, 28, 15, 35, 26, 26, 29, 12, 11]], dtype=int32)

In [47]:
arr1 = np.random.randint(10,40,(10,10))
print(arr1)

[[30 12 26 22 35 37 36 26 18 13]
 [35 17 25 15 38 14 13 24 35 31]
 [35 11 11 32 25 33 25 36 26 37]
 [14 31 32 10 23 18 39 15 15 30]
 [39 39 10 11 36 31 29 36 21 38]
 [12 37 22 30 37 27 32 33 31 20]
 [12 14 23 29 27 13 24 39 12 13]
 [35 25 20 15 35 39 38 11 26 33]
 [16 11 20 29 37 39 17 31 25 34]
 [10 31 25 38 12 36 37 11 32 15]]


In [48]:
print(arr1)

[[30 12 26 22 35 37 36 26 18 13]
 [35 17 25 15 38 14 13 24 35 31]
 [35 11 11 32 25 33 25 36 26 37]
 [14 31 32 10 23 18 39 15 15 30]
 [39 39 10 11 36 31 29 36 21 38]
 [12 37 22 30 37 27 32 33 31 20]
 [12 14 23 29 27 13 24 39 12 13]
 [35 25 20 15 35 39 38 11 26 33]
 [16 11 20 29 37 39 17 31 25 34]
 [10 31 25 38 12 36 37 11 32 15]]


In [49]:
arr1[5]

array([12, 37, 22, 30, 37, 27, 32, 33, 31, 20], dtype=int32)